### ISSUE TITLE
map export

### ISSUE THREAD

**Issue by Juuustin** [Little-Potato-1990/localization_in_auto_driving#10]
Hi, 
Is it possible to export the map showed in Rviz?
Thank you very much!

**Comment by Little-Potato-1990** [comment]
Yes, it is
when mapping, run this
"rosservice call /optimize_map"
it will optimize the map, and show the optimized map in rviz.  
and then run this
"rosservice call /save_map"
it will save the optimized map in your own directory

**Comment by Juuustin** [comment]
Make sense
