### ISSUE TITLE
tag 3.0代码编译报错

### ISSUE THREAD

**Issue by oldwang-ai** [Little-Potato-1990/localization_in_auto_driving#17]
为什么编译会提示报如下错误呢？只有一个main函数。
![error](https://user-images.githubusercontent.com/39984818/99384456-64a6d900-290a-11eb-91bd-e90441bd255a.png)

**Comment by qianqianzige** [comment]
一样的错误，还没找到原因

**Comment by oldwang-ai** [comment]
用catkin_make编译。

**Comment by Zhaohuanfeng** [comment]
你好,请问在哪个位置catkin_make
