### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by autoperson** [Little-Potato-1990/localization_in_auto_driving#4]
编译出现错误：
front_end.cpp:(.text._ZN4YAML18TypedBadConversionIfED2Ev[_ZN4YAML18TypedBadConversionIfED5Ev]+0xf): undefined reference to `YAML::BadConversion::~BadConversion()'
请问你装的yaml-cpp是什么版本的？@Little-Potato-1990

**Comment by Little-Potato-1990** [comment]
我是ubuntu 16.04 装 ros-kinetic时自动安装的yaml版本

**Comment by Little-Potato-1990** [comment]
这个yaml读写，对yaml版本要求确实挺严格的
