### ISSUE TITLE
偶尔会出现Eigen对齐报错

### ISSUE THREAD

**Issue by yzbiao** [Little-Potato-1990/localization_in_auto_driving#6]
front_end_node: /usr/local/include/eigen3/Eigen/src/Core/DenseStorage.h:128: Eigen::internal::plain_array<T, Size, MatrixOrArrayOptions, 32>::plain_array() [with T = float; int Size = 16; int MatrixOrArrayOptions = 0]: Assertion `(internal::UIntPtr(eigen_unaligned_array_assert_workaround_gcc47(array)) & (31)) == 0 && "this assertion is explained here: " "http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html" " **** READ THIS WEB PAGE !!! ****"' failed.
不定时出现，使用了上面eigen网页的办法能够解决，但运行时偶尔会出现，重新编译又不会出现，不知道有没有什么好的解决办法。

**Comment by caiduoduo12138** [comment]
ros节点报错？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yzbiao"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月22日(星期三) 晚上9:52
收件人:&nbsp;"Little-Potato-1990/localization_in_auto_driving"<localization_in_auto_driving@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Little-Potato-1990/localization_in_auto_driving] 偶尔会出现Eigen对齐报错 (#6)





 
front_end_node: /usr/local/include/eigen3/Eigen/src/Core/DenseStorage.h:128: Eigen::internal::plain_array<T, Size, MatrixOrArrayOptions, 32&gt;::plain_array() [with T = float; int Size = 16; int MatrixOrArrayOptions = 0]: Assertion `(internal::UIntPtr(eigen_unaligned_array_assert_workaround_gcc47(array)) &amp; (31)) == 0 &amp;&amp; "this assertion is explained here: " "http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html" " **** READ THIS WEB PAGE !!! ****"' failed.
 不定时出现，使用了上面eigen网页的办法能够解决，但运行时偶尔会出现，重新编译又不会出现，不知道有没有什么好的解决办法。

**Comment by LukyBird** [comment]
我也发生过这个问题，我最后的解决方法：由于你电脑中装的Eigen版本跟本程序放在third_party中的eigen版本不对应.

**Comment by yzbiao** [comment]
> 我也发生过这个问题，我最后的解决方法：由于你电脑中装的Eigen版本跟本程序放在third_party中的eigen版本不对应.



> 我也发生过这个问题，我最后的解决方法：由于你电脑中装的Eigen版本跟本程序放在third_party中的eigen版本不对应.

**Comment by yzbiao** [comment]
> 我也发生过这个问题，我最后的解决方法：由于你电脑中装的Eigen版本跟本程序放在third_party中的eigen版本不对应.

我修改了CMakeLIsts.txt，直接include本地的eigen头文件，还是会有问题。编译完成后，一旦运行报错我就重新运行，重新运行几次后可以正常运行，关了之后再运行又会报错。

**Comment by Little-Potato-1990** [comment]
除了本程序用的eigen版本指向third_party以外，本程序所依赖的库在编译安装的时候，也要使用third_party对应的eigen版本，不然也会发生版本冲突。
当然，引起这样的现象肯定是我没处理好造成的，如果处理好的话，不会对eigen版本有这么严格的要求。

**Comment by yzbiao** [comment]
> 除了本程序用的eigen版本指向third_party以外，本程序所依赖的库在编译安装的时候，也要使用third_party对应的eigen版本，不然也会发生版本冲突。
> 当然，引起这样的现象肯定是我没处理好造成的，如果处理好的话，不会对eigen版本有这么严格的要求。

感谢乾哥的回复，跟着大佬学到很多，祝你工作顺利！

**Comment by xiaoxueshengyao** [comment]
https://gitlab.com/libeigen/eigen/-/issues/1049
可以参考下这个
