### ISSUE TITLE
tap5.0 rosluanch错误

### ISSUE THREAD

**Issue by FishInWave** [Little-Potato-1990/localization_in_auto_driving#8]
我尝试着一个一个Tag运行，看看每一次的优化。
在git clone 5.0版本，并catkin_make后，roslaunch  front_end.launch后，报告process has died。我不太清楚是哪里的问题，因为我并没有对代码做任何的修改。完整的信息如下：

> hurricanezj@ZhaoJie-Alienware-17-R4:~/catkin_ws$ roslaunch lidar_localization front_end.launch 
... logging to /home/hurricanezj/.ros/log/99c924c4-88fd-11ea-91e7-9cb6d0effb2d/roslaunch-ZhaoJie-Alienware-17-R4-25122.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

  started roslaunch server http://ZhaoJie-Alienware-17-R4:34547/

  SUMMARY
  ========

PARAMETERS
* /rosdistro: kinetic
* /rosversion: 1.12.14

  NODES
   /
      front_end_node (lidar_localization/front_end_node)
       rviz (rviz/rviz)

  ROS_MASTER_URI=http://localhost:11311

process[rviz-1]: started with pid [25139]
process[front_end_node-2]: started with pid [25140]
[front_end_node-2] process has died [pid 25140, exit code -11, cmd /home/hurricanezj/catkin_ws/devel/lib/lidar_localization/front_end_node __name:=front_end_node __log:=/home/hurricanezj/.ros/log/99c924c4-88fd-11ea-91e7-9cb6d0effb2d/front_end_node-2.log].
log file: /home/hurricanezj/.ros/log/99c924c4-88fd-11ea-91e7-9cb6d0effb2d/front_end_node-2*.log

希望您可以抽空帮我看看。运行环境为Ubuntu16.04，ros-kinetic ，前面的tag3.0与tag4.0均正常。

**Comment by FishInWave** [comment]
我查询了一些资料，并用GDB来查看，可能的原因指向了：对空指针进行了操作。

**Comment by Little-Potato-1990** [comment]
这种提示信息没有直接给出报错的位置，一般我遇到这种问题，都是在程序里加打印信息来定位出错位置在哪，找到位置，原因就很好分析了。
另外，你每次下载一个新的tag，重新编译的时候，有没有把之前的devel和build删掉

**Comment by FishInWave** [comment]
我发现cmake的时候有两条报错被我忽略了，与vtk和saveMap_gencpp有关。全文如下：
-- ==> add_subdirectory(catkin_hdl_slam/src/hdl_graph_slam)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
--   date_time
--   iostreams
--   serialization
--   chrono
--   atomic
--   regex
** WARNING ** io features related to pcap will be disabled
** WARNING ** io features related to png will be disabled
-- The imported target "vtkRenderingPythonTkWidgets" references the file
   "/usr/lib/x86_64-linux-gnu/libvtkRenderingPythonTkWidgets.so"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-6.2/VTKTargets.cmake"
but not all the files it references.

-- The imported target "vtk" references the file
   "/usr/bin/vtk"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-6.2/VTKTargets.cmake"
but not all the files it references.


-- Configuring done
CMake Warning (dev) at localization_in_auto_driving/lidar_localization/CMakeLists.txt:53 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "saveMap_gencpp" of target "front_end_node" does not
  exist.
This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by FishInWave** [comment]
关于vtk的那个错误，通过建立软链接解决了。但是savaMap_gencpp我还是不太清楚在哪个部分进行修改

**Comment by FishInWave** [comment]
通过加注释，定位到问题出在front_end_node.cpp中的:
_front_end_flow_ptr = std::make_shared<FrontEndFlow>(nh);

**Comment by Little-Potato-1990** [comment]
程序里是这句，你是程序变了，还是这个回答里写错了
_front_end_flow_ptr = std::make_shared<FrontEndFlow>(nh);

**Comment by Little-Potato-1990** [comment]
如果还没解决，你就在知乎上私信我吧，github我上的少
